#!/usr/bin/env python3
"""
Rebuild dist/rnspectrax-standalone.html from the modular source.

The single-file build exists so a collaborator or reviewer can be handed one
attachment and open it. Run this after changing anything in css/ or js/:

    python3 build-standalone.py
"""
import base64
import os
import re

os.chdir(os.path.dirname(os.path.abspath(__file__)))
src = open('index.html', encoding='utf-8').read()


def inline_css(match):
    path = match.group(1)
    return '<style>\n/* %s */\n%s\n</style>' % (path, open(path, encoding='utf-8').read())


def inline_js(match):
    path = match.group(1)
    return '<script>\n/* %s */\n%s\n</script>' % (path, open(path, encoding='utf-8').read())


src = re.sub(r'<link href="(css/[^"]+)" rel="stylesheet"/>', inline_css, src)
src = re.sub(r'<link rel="stylesheet" href="(css/[^"]+)"\s*/?>', inline_css, src)
src = re.sub(r'<script src="(js/[^"]+)"></script>', inline_js, src)

icon = base64.b64encode(open('assets/favicon.svg', encoding='utf-8').read().encode()).decode()
src = src.replace('<link rel="icon" href="assets/favicon.svg" type="image/svg+xml"/>',
                  '<link rel="icon" href="data:image/svg+xml;base64,%s" type="image/svg+xml"/>' % icon)
src = src.replace('href="docs/USER_MANUAL.md"',
                  'href="https://github.com/rakeshnaik/rnspectrax/blob/main/docs/USER_MANUAL.md"')

banner = ("<!-- RNSpectraX 3.1 — single-file build.\n"
          "     Generated by build-standalone.py. Do not edit by hand:\n"
          "     edit the modular source and rebuild. -->\n")

os.makedirs('dist', exist_ok=True)
out = 'dist/rnspectrax-standalone.html'
open(out, 'w', encoding='utf-8').write(banner + src)
print('Wrote %s (%.0f KB)' % (out, os.path.getsize(out) / 1024))
